# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_brtlib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_brtlib')
    _brtlib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_brtlib', [dirname(__file__)])
        except ImportError:
            import _brtlib
            return _brtlib
        try:
            _mod = imp.load_module('_brtlib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _brtlib = swig_import_helper()
    del swig_import_helper
else:
    import _brtlib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def brt_path(relpath):
    return _brtlib.brt_path(relpath)
brt_path = _brtlib.brt_path

def brt_whitelist_env(env_name):
    return _brtlib.brt_whitelist_env(env_name)
brt_whitelist_env = _brtlib.brt_whitelist_env

def brt_setup_user_ns():
    return _brtlib.brt_setup_user_ns()
brt_setup_user_ns = _brtlib.brt_setup_user_ns

def brt_fatal(format):
    return _brtlib.brt_fatal(format)
brt_fatal = _brtlib.brt_fatal

def brt_whitelist_envs_from_env(export_env):
    return _brtlib.brt_whitelist_envs_from_env(export_env)
brt_whitelist_envs_from_env = _brtlib.brt_whitelist_envs_from_env

def brt_bind_mount(src, dst):
    return _brtlib.brt_bind_mount(src, dst)
brt_bind_mount = _brtlib.brt_bind_mount

def brt_setup_mount_ns():
    return _brtlib.brt_setup_mount_ns()
brt_setup_mount_ns = _brtlib.brt_setup_mount_ns

def brt_chdir(newdir):
    return _brtlib.brt_chdir(newdir)
brt_chdir = _brtlib.brt_chdir

def brt_chroot(rootfs):
    return _brtlib.brt_chroot(rootfs)
brt_chroot = _brtlib.brt_chroot
# This file is compatible with both classic and new-style classes.


